Repository TimBuilding/wisecare, pull requests merged in 2024-09, with the labels that each got.

#114 feat(users): add update function on postgres
  supabase/migrations/20240901051840_user_profile_function_update.sql
Labels: enhancement

#115 feat(users): add edit user form
  src/app/(dashboard)/admin/users/add-user-form.tsx
  src/app/(dashboard)/admin/users/add-user.tsx
  src/app/(dashboard)/admin/users/create/add-user-form.tsx
  src/app/(dashboard)/admin/users/create/add-user.tsx
  src/app/(dashboard)/admin/users/edit/edit-user-form.tsx
  src/app/(dashboard)/admin/users/edit/edit-user.tsx
  src/app/(dashboard)/admin/users/page.tsx
  src/app/(dashboard)/admin/users/user-list.tsx
  src/queries/get-users.ts
Labels: enhancement

#116 feat(users): add update api route
  src/app/(dashboard)/admin/users/edit/edit-user-form.tsx
  src/app/api/users/route.ts
Labels: enhancement

#117 feat(users): add delete user function
  src/app/(dashboard)/admin/users/edit/delete-user.tsx
  src/app/(dashboard)/admin/users/edit/edit-user-form.tsx
  src/app/api/users/route.ts
Labels: enhancement

#118 TIM-366 feat(logs): add activity log page
  src/app/(dashboard)/admin/logs/activity-table.tsx
  src/app/(dashboard)/admin/logs/page.tsx
  src/components/layout/admin-navigation.tsx
Labels: enhancement

#119 TIM-367 feat(logs): add activity_log table
  supabase/migrations/20240902085312_add_activity_logs_table.sql
Labels: enhancement

#120 TIM-365 feat(logs): add activity log data fetching
  src/app/(dashboard)/admin/logs/activity-table.tsx
  src/app/(dashboard)/admin/logs/page.tsx
  src/queries/get-activity-log.ts
  src/types/database.types.ts
Labels: enhancement

#124 TIM-351 fix(users): validation and loading state on user creation
  src/app/(dashboard)/admin/users/create/add-user-form.tsx
  src/app/(dashboard)/admin/users/user-schema.ts
Labels: enhancement

#126 feat(types): add edit type dialog
  src/app/(dashboard)/admin/types/edit-type.tsx
  src/app/(dashboard)/admin/types/type-list.tsx
Labels: enhancement

#127 TIM-371 feat(types): add edit types backend connection
  src/app/(dashboard)/admin/types/edit-type.tsx
  src/app/(dashboard)/admin/types/type-list.tsx
  supabase/migrations/20240903064911_add_update_rls_to_types_tables.sql
Labels: enhancement

#128 TIM-372 fix(users): total count on header
  src/app/(dashboard)/admin/users/page.tsx
  src/app/(dashboard)/admin/users/user-list-header.tsx
Labels: enhancement

#129 TIM-373 fix(agents): total count on header
  src/app/(dashboard)/admin/agents/agents-count.tsx
Labels: enhancement

#130 TIM-348 feat(users): add resend email confirmation for admin
  src/app/(dashboard)/admin/users/edit/confirm-email.tsx
  src/app/(dashboard)/admin/users/edit/edit-user-form.tsx
Labels: enhancement

#131 TIM-374(supabase): fix security warnings
  supabase/migrations/20240904050640_fix_search_path_warnings.sql
Labels: bug

#132 TIM-375 BREAKING CHANGE: allow null values on accounts columns
  src/app/(dashboard)/(home)/accounts/accounts-schema.ts
  src/app/(dashboard)/(home)/accounts/forms/marketing-inputs.tsx
  src/app/(dashboard)/(home)/pending/forms/disabled-inputs.tsx
  src/app/(dashboard)/(home)/pending/forms/pending-inputs.tsx
  src/app/(dashboard)/(home)/pending/forms/pending-schema.ts
  src/types/database.types.ts
  supabase/migrations/20240904102255_allow_null_values_to_accounts_table.sql
Labels: enhancement

#133 feat(agents): add edit agent form
  src/app/(dashboard)/admin/agents/agents-list.tsx
  src/app/(dashboard)/admin/agents/create/add-agent-form.tsx
  src/app/(dashboard)/admin/agents/create/add-agent.tsx
  src/app/(dashboard)/admin/agents/edit/edit-agent-form.tsx
  src/app/(dashboard)/admin/agents/page.tsx
Labels: enhancement

#134 feat(agents): add edit agents form submit
  src/app/(dashboard)/admin/agents/agents-list.tsx
  src/app/(dashboard)/admin/agents/edit/edit-agent-form.tsx
  src/queries/get-agents.ts
Labels: enhancement

#135 TIM-379 feat(agents): add delete agent functionality
  src/app/(dashboard)/admin/agents/create/delete-agent.tsx
  src/app/(dashboard)/admin/agents/edit/edit-agent-form.tsx
Labels: enhancement

#136 TIM-162 feat(auth): add reset-password feature
  src/app/(auth)/forgot-password/forgot-password-form.tsx
  src/app/(auth)/forgot-password/forgot-password-schema.ts
  src/app/(auth)/forgot-password/page.tsx
  src/app/(auth)/sign-in/sign-in-form.tsx
Labels: enhancement

#137 TIM-176 feat(accounts): add saving of column visibility
  src/app/(dashboard)/(home)/accounts/data-table.tsx
  src/app/(dashboard)/(home)/pending/data-table.tsx
  src/components/table-view-options.tsx
  src/types/database.types.ts
  supabase/migrations/20240918024102_column_visibility_table.sql
Labels: enhancement

#138 TIM-382 feat(auth): add captcha on login page
  package.json
  pnpm-lock.yaml
  src/app/(auth)/sign-in/sign-in-form.tsx
Labels: enhancement

#139 TIM-383 feat(auth): add captcha on forgot password page
  src/app/(auth)/forgot-password/forgot-password-form.tsx
Labels: enhancement

#140 TIM-385 fix(accounts): default values to be null on marketing form
  src/app/(dashboard)/(home)/accounts/add-account-form.tsx
  src/app/(dashboard)/(home)/pending/update-pending-form.tsx
Labels: enhancement

#142 TIM-386 fix(pending): fetchg null values
  src/app/(dashboard)/(home)/pending/forms/disabled-inputs.tsx
Labels: enhancement

#143 TIM-390 BREAKING: change employees table columns
  src/app/(dashboard)/(home)/accounts/(Personnel)/[id]/employees-information.tsx
  src/app/(dashboard)/(home)/accounts/(Personnel)/[id]/employees-page.tsx
  src/types/database.types.ts
  supabase/migrations/20240926041613_change_company_employees_table.sql
Labels: enhancement

#144 TIM-391 REFACTOR: employees details
  src/app/(dashboard)/(home)/accounts/(Personnel)/[id]/employees-information.tsx
  src/app/(dashboard)/(home)/accounts/(Personnel)/[id]/employees-page.tsx
  src/queries/get-employee-inputs.ts
Labels: enhancement

#145 TIM-392 REFACTOR: add employee form
  src/app/(dashboard)/(home)/accounts/(Personnel)/[id]/employees-add-personnel-button.tsx
  src/app/(dashboard)/(home)/accounts/(Personnel)/[id]/employees-add-personnel-form.tsx
  src/app/(dashboard)/(home)/accounts/(Personnel)/[id]/employees-add-personnel-schema.ts
Labels: enhancement

#146 TIM-394 feat(employees): add loading state to employees form
  src/app/(dashboard)/(home)/accounts/(Personnel)/[id]/employees-add-personnel-button.tsx
  src/app/(dashboard)/(home)/accounts/(Personnel)/[id]/employees-add-personnel-form.tsx
  src/queries/get-employee-inputs.ts
Labels: enhancement

#147 TIM-397 fix(profile): null values error
  src/app/(dashboard)/(home)/accounts/(Personnel)/[id]/company-HMO-information.tsx
  src/app/(dashboard)/(home)/accounts/(Personnel)/[id]/company-account-information.tsx
  src/app/(dashboard)/(home)/accounts/(Personnel)/[id]/company-contract-information.tsx
  src/app/(dashboard)/(home)/accounts/(Personnel)/[id]/company-header.tsx
Labels: bug

#148 fix(profile): type error
  src/app/(dashboard)/(home)/accounts/(Personnel)/[id]/company-HMO-information.tsx
Labels: bug, hotfix

#149 TIM-395 fix(employees): null values on employee details
  src/app/(dashboard)/(home)/accounts/(Personnel)/[id]/company-account-information.tsx
  src/app/(dashboard)/(home)/accounts/(Personnel)/[id]/employees-information.tsx
  src/app/(dashboard)/(home)/accounts/(Personnel)/[id]/employees-page.tsx
Labels: bug

#150 TIM-387 Add forms and context to edit company details
  src/app/(dashboard)/(home)/accounts/(Personnel)/[id]/company-HMO-information.tsx
  src/app/(dashboard)/(home)/accounts/(Personnel)/[id]/company-about.tsx
  src/app/(dashboard)/(home)/accounts/(Personnel)/[id]/company-account-information.tsx
  src/app/(dashboard)/(home)/accounts/(Personnel)/[id]/company-cancel-button.tsx
  src/app/(dashboard)/(home)/accounts/(Personnel)/[id]/company-contract-information.tsx
  src/app/(dashboard)/(home)/accounts/(Personnel)/[id]/company-edit-button.tsx
  src/app/(dashboard)/(home)/accounts/(Personnel)/[id]/company-edit-provider.tsx
  src/app/(dashboard)/(home)/accounts/(Personnel)/[id]/company-financial-information.tsx
  src/app/(dashboard)/(home)/accounts/(Personnel)/[id]/company-information.tsx
  src/app/(dashboard)/(home)/accounts/(Personnel)/[id]/company-page.tsx
Labels: bug
